name: Codacy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '30 12 * * 4'

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@4.0.0
        with:
#           project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          codacy-api-base-url: https://api.codacy.com/api/v3
          directory: plugins
          clang-tidy-output: path/to/output
          faux-pas-output: path/to/output
          upload: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
