name: Gradle Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Gradle Modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-2/
            ~/.gradle/caches/build-cache-1/
            ~/.gradle/caches/signatures/
            ~/.gradle/caches/keyrings/
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle (fast)
        if: ${{ github.event_name != 'schedule' }}
        run: gradle build -Dfast.test=true

      - name: Build with Gradle (all)
        if: ${{ github.event_name == 'schedule' }}
        run: gradle build

      - name: Upload Coverage Reports
        run: |
          gradle jacocoTestReport
          bash <(curl -s https://codecov.io/bash)

      - name: Cleanup Gradle Cache
        # Cleans up the Gradle caches before being cached
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
